apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
  labels:
    purpose: migrations
spec:
  backoffLimit: 1             # количество попыток += 1
  activeDeadlineSeconds: 120  # общее время неуспеха и удаление
  ttlSecondsAfterFinished: 1
  template:
    metadata:
      labels:
        purpose: django-migrations
    spec:
      restartPolicy: Never
      containers:
        - name: django-app
          image: django-app:1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: django-config-file
          command: [ "/bin/sh","-c" ]
          args: [ "python manage.py migrate && python manage.py createsuperuser --no-input" ]
#          command:
#            - python
#            - manage.py
#            - migrate