apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-hosts

spec:
  rules:
  - hots: star-burger.test'
    http:
      paths:
        - backend:
            serviceName: django-service
            servicePort: 80