apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    service: test-django-service
spec:
  type: NodePort
  selector:
    name: test-django-pod
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-django-deployment
  labels:
    app: test-django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: test-django-pod
  template:
    metadata:
      labels:
        name: test-django-pod
    spec:
      containers:
        - name: django-app
          image: mulchus/django-app:cec55e78
          envFrom:         # это просто взятие переменных из ConfigMap
            - configMapRef:
                name: django-config-file
          ports:
            - containerPort: 80